# Generated by Django 3.0.3 on 2020-04-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(blank=True, max_length=20, null=True)),
                ('option_two', models.CharField(blank=True, max_length=20, null=True)),
                ('option_three', models.CharField(blank=True, max_length=20, null=True)),
                ('count_op1', models.IntegerField(blank=True, default=0, null=True)),
                ('count_op2', models.IntegerField(blank=True, default=0, null=True)),
                ('count_op3', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
